const modules = [
  {
    id: 1,
    title: "Introdução ao JavaScript",
    percentage: 80,
    lessons: [
      {
        id: 0,
        title: "O que é JavaScript?",
        slug: "o-que-e-javascript",
        watched: true,
        description:
          "Uma introdução à linguagem JavaScript e seu papel no desenvolvimento web.",
        duration: 1200,
      },
      {
        id: 1,
        title: "Inserindo JavaScript no HTML",
        slug: "inserindo-javascript-no-html",
        watched: true,
        description:
          "Aprenda como conectar o JavaScript ao seu HTML usando tags <script>.",
        duration: 1000,
      },
      {
        id: 2,
        title: "Console e comentários",
        slug: "console-e-comentarios",
        watched: false,
        description:
          "Utilizando o console do navegador e boas práticas de comentários.",
        duration: 800,
      },
      {
        id: 3,
        title: "Ambientes de desenvolvimento",
        slug: "ambientes-de-desenvolvimento",
        watched: false,
        description:
          "Ferramentas e editores mais comuns para programar em JavaScript.",
        duration: 1000,
      },
      {
        id: 4,
        title: "Executando JS no navegador e no Node.js",
        slug: "executando-js-navegador-node",
        watched: false,
        description: "Aprenda como rodar códigos em diferentes ambientes.",
        duration: 1100,
      },
      {
        id: 5,
        title: "História do JavaScript",
        slug: "historia-do-javascript",
        watched: false,
        description: "Conheça a origem e evolução do JavaScript desde 1995.",
        duration: 900,
      },
      {
        id: 6,
        title: "Sintaxe básica",
        slug: "sintaxe-basica",
        watched: false,
        description: "Entendendo a estrutura básica de um script JavaScript.",
        duration: 1000,
      },
    ],
  },
  {
    id: 2,
    title: "Variáveis e Tipos de Dados",
    percentage: 60,
    lessons: [
      {
        id: 0,
        title: "Declaração de variáveis",
        slug: "declaracao-de-variaveis",
        watched: true,
        description: "Diferenças entre var, let e const, e quando usá-los.",
        duration: 1800,
      },
      {
        id: 1,
        title: "Tipos de dados primitivos",
        slug: "tipos-de-dados-primitivos",
        watched: true,
        description: "Explorando strings, números, booleans, null e undefined.",
        duration: 1100,
      },
      {
        id: 2,
        title: "Conversão de tipos",
        slug: "conversao-de-tipos",
        watched: false,
        description:
          "Como converter dados entre diferentes tipos em JavaScript.",
        duration: 900,
      },
      {
        id: 3,
        title: "Template literals",
        slug: "template-literals",
        watched: false,
        description: "Uso de crases para interpolação de variáveis em strings.",
        duration: 600,
      },
      {
        id: 4,
        title: "Verificando tipos com typeof",
        slug: "verificando-tipos-com-typeof",
        watched: false,
        description:
          "Utilize o operador typeof para identificar o tipo de dado.",
        duration: 800,
      },
      {
        id: 5,
        title: "Valores especiais: NaN, Infinity",
        slug: "valores-especiais-nan-infinity",
        watched: false,
        description: "Aprenda o que são e como lidar com NaN e Infinity.",
        duration: 700,
      },
    ],
  },
  {
    id: 3,
    title: "Operadores e Expressões",
    percentage: 40,
    lessons: [
      {
        id: 0,
        title: "Operadores Aritméticos",
        slug: "operadores-aritmeticos",
        watched: true,
        description: "Soma, subtração, multiplicação, divisão e módulo.",
        duration: 900,
      },
      {
        id: 1,
        title: "Operadores Lógicos e de Comparação",
        slug: "operadores-logicos-e-comparacao",
        watched: false,
        description: "Entenda os operadores &&, ||, ! e ==, ===, !=, !==.",
        duration: 1600,
      },
      {
        id: 2,
        title: "Operadores de atribuição",
        slug: "operadores-de-atribuicao",
        watched: false,
        description: "Conheça operadores como +=, -=, *=, /= e outros.",
        duration: 800,
      },
      {
        id: 3,
        title: "Precedência de operadores",
        slug: "precedencia-de-operadores",
        watched: false,
        description:
          "Aprenda a ordem de execução dos operadores em expressões.",
        duration: 1000,
      },
    ],
  },
  {
    id: 4,
    title: "Controle de Fluxo",
    percentage: 30,
    lessons: [
      {
        id: 0,
        title: "If, Else e Else If",
        slug: "if-else-else-if",
        watched: false,
        description: "Fluxo condicional com if/else e boas práticas.",
        duration: 1200,
      },
      {
        id: 1,
        title: "Switch",
        slug: "switch",
        watched: false,
        description: "Como usar o switch para múltiplas condições.",
        duration: 1000,
      },
      {
        id: 2,
        title: "Truthy e Falsy",
        slug: "truthy-e-falsy",
        watched: false,
        description:
          "Entenda valores que retornam verdadeiro ou falso implicitamente.",
        duration: 700,
      },
      {
        id: 3,
        title: "Operador ternário",
        slug: "operador-ternario",
        watched: false,
        description:
          "Uso do operador condicional ternário em expressões simples.",
        duration: 800,
      },
    ],
  },
  {
    id: 5,
    title: "Loops e Iterações",
    percentage: 0,
    lessons: [
      {
        id: 0,
        title: "For e While",
        slug: "for-e-while",
        watched: false,
        description: "Estruturas de repetição for, while e do...while.",
        duration: 1800,
      },
      {
        id: 1,
        title: "ForEach e Map",
        slug: "foreach-e-map",
        watched: false,
        description: "Iterando arrays com métodos modernos do JavaScript.",
        duration: 1300,
      },
      {
        id: 2,
        title: "Break e Continue",
        slug: "break-e-continue",
        watched: false,
        description: "Controlando a execução de loops com break e continue.",
        duration: 900,
      },
      {
        id: 3,
        title: "Loop aninhado",
        slug: "loop-aninhado",
        watched: false,
        description: "Como criar e controlar loops dentro de outros loops.",
        duration: 1000,
      },
    ],
  },
  {
    id: 6,
    title: "Funções",
    percentage: 0,
    lessons: [
      {
        id: 0,
        title: "Funções Declaradas e Expressões",
        slug: "funcoes-declaradas-e-expressoes",
        watched: false,
        description: "Declaração de funções e uso de funções como variáveis.",
        duration: 1100,
      },
      {
        id: 1,
        title: "Arrow Functions",
        slug: "arrow-functions",
        watched: false,
        description: "Como usar arrow functions e entender o `this`.",
        duration: 1000,
      },
      {
        id: 2,
        title: "Parâmetros e argumentos",
        slug: "parametros-e-argumentos",
        watched: false,
        description: "Como passar e receber dados em funções.",
        duration: 1000,
      },
      {
        id: 3,
        title: "Funções de alta ordem",
        slug: "funcoes-de-alta-ordem",
        watched: false,
        description: "Funções que recebem ou retornam outras funções.",
        duration: 900,
      },
      {
        id: 4,
        title: "Funções recursivas",
        slug: "funcoes-recursivas",
        watched: false,
        description:
          "O que é recursão e como usar funções que se chamam a si mesmas.",
        duration: 1200,
      },
    ],
  },
];

export { modules };
