import { ICourse } from "./interfaces/course";

const courses: ICourse[] = [
  {
    id: 0,
    title: "JavaScript do Zero ao Avançado",
    price: 149.9,
    details: {
      totalTime: 40012,
      lessonCount: 21,
      category: "prog",
      evaluation: 4.4,
    },
    slug: "javascript-do-zero-ao-avancado",
    thumbnail: "/js.jpeg",
    status: "ACTIVE",
    modules: [
      {
        id: 1,
        title: "Fundamentos do JavaScript",
        percentage: 90,
        lessons: [
          {
            id: 0,
            title: "O que é JavaScript?",
            slug: "o-que-e-javascript",
            watched: true,
            description: "Entenda o propósito e a origem do JavaScript.",
            duration: 900,
          },
          {
            id: 1,
            title: "Sintaxe e operadores básicos",
            slug: "sintaxe-operadores-basicos",
            watched: true,
            description: "Explora operadores, valores, expressões e estrutura.",
            duration: 1100,
          },
        ],
      },
      {
        id: 2,
        title: "Funções e Escopos",
        percentage: 70,
        lessons: [
          {
            id: 0,
            title: "Funções declaradas vs expressas",
            slug: "funcoes-declaradas-vs-expressas",
            watched: false,
            description: "Compreendendo os diferentes tipos de funções.",
            duration: 1200,
          },
          {
            id: 1,
            title: "Arrow functions",
            slug: "arrow-functions",
            watched: false,
            description: "Sintaxe moderna e implicações com `this`.",
            duration: 1000,
          },
        ],
      },
      {
        id: 3,
        title: "Manipulação do DOM",
        percentage: 50,
        lessons: [
          {
            id: 0,
            title: "Selecionando elementos",
            slug: "selecionando-elementos",
            watched: false,
            description: "getElementById, querySelector e muito mais.",
            duration: 1300,
          },
          {
            id: 1,
            title: "Eventos no navegador",
            slug: "eventos-no-navegador",
            watched: false,
            description: "Como lidar com interações do usuário.",
            duration: 1500,
          },
        ],
      },
    ],
  },
  {
    id: 1,
    title: "Design UI/UX para Iniciantes",
    price: 99.9,
    details: {
      totalTime: 21000,
      lessonCount: 16,
      category: "design",
      evaluation: 3.9,
    },
    slug: "design-ui-ux-para-iniciantes",
    thumbnail: "/node.png",
    status: "ENROLLED",
    modules: [
      {
        id: 1,
        title: "Fundamentos de UI/UX",
        percentage: 100,
        lessons: [
          {
            id: 0,
            title: "Diferença entre UI e UX",
            slug: "diferenca-ui-ux",
            watched: true,
            description: "Entenda os papéis da interface e experiência.",
            duration: 900,
          },
          {
            id: 1,
            title: "Princípios de design visual",
            slug: "principios-design-visual",
            watched: true,
            description: "Contraste, repetição, alinhamento e proximidade.",
            duration: 1000,
          },
        ],
      },
      {
        id: 2,
        title: "Ferramentas de Design",
        percentage: 70,
        lessons: [
          {
            id: 0,
            title: "Introdução ao Figma",
            slug: "introducao-ao-figma",
            watched: true,
            description: "Conhecendo o ambiente e recursos do Figma.",
            duration: 1100,
          },
          {
            id: 1,
            title: "Wireframes e protótipos",
            slug: "wireframes-e-prototipos",
            watched: false,
            description: "Como planejar e estruturar suas telas.",
            duration: 1300,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Python para Análise de Dados",
    price: 139.9,
    details: {
      totalTime: 32000,
      lessonCount: 18,
      category: "data",
      evaluation: 4.6,
    },
    slug: "python-para-analise-de-dados",
    thumbnail: "/ts.png",
    status: "ACTIVE",
    modules: [
      {
        id: 1,
        title: "Introdução ao Python",
        percentage: 100,
        lessons: [
          {
            id: 0,
            title: "Instalando Python e Jupyter",
            slug: "instalando-python-e-jupyter",
            watched: true,
            description: "Preparando o ambiente de desenvolvimento.",
            duration: 1000,
          },
          {
            id: 1,
            title: "Sintaxe básica do Python",
            slug: "sintaxe-basica-do-python",
            watched: true,
            description: "Comandos, indentação e boas práticas.",
            duration: 1100,
          },
        ],
      },
      {
        id: 2,
        title: "Trabalhando com Pandas",
        percentage: 50,
        lessons: [
          {
            id: 0,
            title: "DataFrames e Séries",
            slug: "dataframes-e-series",
            watched: false,
            description: "Manipulando estruturas de dados com pandas.",
            duration: 1400,
          },
          {
            id: 1,
            title: "Leitura de CSVs",
            slug: "leitura-de-csvs",
            watched: false,
            description: "Como importar dados externos no pandas.",
            duration: 1300,
          },
        ],
      },
      {
        id: 3,
        title: "Visualização de Dados",
        percentage: 30,
        lessons: [
          {
            id: 0,
            title: "Gráficos com Matplotlib",
            slug: "graficos-com-matplotlib",
            watched: false,
            description: "Criação de gráficos básicos com matplotlib.",
            duration: 1200,
          },
          {
            id: 1,
            title: "Estilizando gráficos",
            slug: "estilizando-graficos",
            watched: false,
            description: "Melhorando aparência e legibilidade dos dados.",
            duration: 1000,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "HTML e CSS Essencial",
    price: 89.9,
    details: {
      totalTime: 24000,
      lessonCount: 18,
      category: "prog",
      evaluation: 4.2,
    },
    slug: "html-css-essencial",
    thumbnail: "/node.png",
    status: "ENROLLED",
    modules: [
      {
        id: 1,
        title: "Começando com HTML",
        percentage: 100,
        lessons: [
          {
            id: 0,
            title: "Estrutura básica de um documento HTML",
            slug: "estrutura-basica-html",
            watched: true,
            description: "Conheça as tags fundamentais de uma página.",
            duration: 900,
          },
          {
            id: 1,
            title: "Tags de texto e imagens",
            slug: "tags-texto-imagens",
            watched: true,
            description: "Utilize texto, imagens e listas com HTML.",
            duration: 1000,
          },
          {
            id: 2,
            title: "Formulários e inputs",
            slug: "formularios-e-inputs",
            watched: false,
            description: "Criação de formulários interativos.",
            duration: 1100,
          },
        ],
      },
      {
        id: 2,
        title: "Estilizando com CSS",
        percentage: 60,
        lessons: [
          {
            id: 0,
            title: "Seletores e propriedades básicas",
            slug: "seletores-css-basico",
            watched: false,
            description: "Aplicando estilos através de seletores.",
            duration: 1200,
          },
          {
            id: 1,
            title: "Layout com Flexbox",
            slug: "layout-flexbox",
            watched: false,
            description: "Organizando elementos com flexbox.",
            duration: 1400,
          },
          {
            id: 2,
            title: "Introdução ao Grid Layout",
            slug: "introducao-grid-layout",
            watched: false,
            description: "Criando layouts com CSS Grid.",
            duration: 1300,
          },
        ],
      },
      {
        id: 3,
        title: "Projeto Prático: Landing Page",
        percentage: 0,
        lessons: [
          {
            id: 0,
            title: "Planejando a estrutura",
            slug: "planejando-estrutura",
            watched: false,
            description: "Como organizar o conteúdo da landing page.",
            duration: 900,
          },
          {
            id: 1,
            title: "Codando a página",
            slug: "codando-pagina",
            watched: false,
            description: "Colocando HTML e CSS em prática.",
            duration: 1600,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "React para Iniciantes",
    price: 159.9,
    details: {
      totalTime: 34000,
      lessonCount: 26,
      category: "prog",
      evaluation: 4.7,
    },
    slug: "react-para-iniciantes",
    thumbnail: "/ts.png",
    status: "DRAFT",
    modules: [
      {
        id: 1,
        title: "Fundamentos do React",
        percentage: 80,
        lessons: [
          {
            id: 0,
            title: "O que é React?",
            slug: "o-que-e-react",
            watched: true,
            description: "Entenda a proposta do React e como ele funciona.",
            duration: 1000,
          },
          {
            id: 1,
            title: "Criando componentes",
            slug: "criando-componentes",
            watched: true,
            description: "Estrutura e composição de componentes funcionais.",
            duration: 1100,
          },
          {
            id: 2,
            title: "Props e Children",
            slug: "props-e-children",
            watched: false,
            description: "Como passar dados entre componentes.",
            duration: 1200,
          },
        ],
      },
      {
        id: 2,
        title: "Trabalhando com Estados e Efeitos",
        percentage: 50,
        lessons: [
          {
            id: 0,
            title: "useState e eventos",
            slug: "usestate-e-eventos",
            watched: false,
            description: "Gerenciando estados locais nos componentes.",
            duration: 1200,
          },
          {
            id: 1,
            title: "useEffect e ciclo de vida",
            slug: "useeffect-ciclo-de-vida",
            watched: false,
            description: "Executando efeitos colaterais com useEffect.",
            duration: 1300,
          },
        ],
      },
      {
        id: 3,
        title: "Consumindo APIs",
        percentage: 0,
        lessons: [
          {
            id: 0,
            title: "Requisições com fetch",
            slug: "fetch-react",
            watched: false,
            description: "Buscando dados de APIs externas.",
            duration: 1300,
          },
          {
            id: 1,
            title: "Renderizando dados dinamicamente",
            slug: "render-dinamico-api",
            watched: false,
            description: "Utilizando os dados da API em listas.",
            duration: 1400,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "Banco de Dados com SQL",
    price: 129.9,
    details: {
      totalTime: 27000,
      lessonCount: 20,
      category: "data",
      evaluation: 4.3,
    },
    slug: "banco-de-dados-com-sql",
    thumbnail: "/js.jpeg",
    status: "PENDING",
    modules: [
      {
        id: 1,
        title: "Introdução ao SQL",
        percentage: 100,
        lessons: [
          {
            id: 0,
            title: "Comandos básicos: SELECT, INSERT",
            slug: "comandos-basicos-sql",
            watched: true,
            description: "Aprenda a buscar e inserir dados.",
            duration: 1100,
          },
          {
            id: 1,
            title: "Atualizando e deletando dados",
            slug: "update-delete-sql",
            watched: true,
            description: "Use UPDATE e DELETE com segurança.",
            duration: 1000,
          },
        ],
      },
      {
        id: 2,
        title: "Relacionamentos e Joins",
        percentage: 40,
        lessons: [
          {
            id: 0,
            title: "Relacionamentos 1:1 e 1:N",
            slug: "relacionamentos-sql",
            watched: false,
            description: "Estruturando tabelas com chaves estrangeiras.",
            duration: 1300,
          },
          {
            id: 1,
            title: "INNER, LEFT e RIGHT JOIN",
            slug: "joins-sql",
            watched: false,
            description: "Combinando dados de múltiplas tabelas.",
            duration: 1400,
          },
        ],
      },
      {
        id: 3,
        title: "Consultas Avançadas",
        percentage: 0,
        lessons: [
          {
            id: 0,
            title: "Funções de agregação",
            slug: "funcoes-agregacao",
            watched: false,
            description: "Usando COUNT, SUM, AVG, MAX e MIN.",
            duration: 1100,
          },
          {
            id: 1,
            title: "GROUP BY e HAVING",
            slug: "group-by-having",
            watched: false,
            description: "Agrupando resultados e filtrando agregações.",
            duration: 1200,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Git e GitHub na Prática",
    price: 59.9,
    details: {
      totalTime: 16000,
      lessonCount: 14,
      category: "tools",
      evaluation: 4.5,
    },
    slug: "git-e-github-na-pratica",
    thumbnail: "/ts.png",
    status: "ENROLLED",
    modules: [
      {
        id: 1,
        title: "Fundamentos do Git",
        percentage: 90,
        lessons: [
          {
            id: 0,
            title: "Git init, add e commit",
            slug: "git-init-add-commit",
            watched: true,
            description: "Primeiros comandos do Git na prática.",
            duration: 1000,
          },
          {
            id: 1,
            title: "Branches e merges",
            slug: "branches-e-merges",
            watched: true,
            description: "Trabalhando com ramificações no Git.",
            duration: 1200,
          },
        ],
      },
      {
        id: 2,
        title: "Trabalhando com GitHub",
        percentage: 50,
        lessons: [
          {
            id: 0,
            title: "Clonando e criando repositórios",
            slug: "clonando-e-criando-repos",
            watched: false,
            description: "Integração local com GitHub.",
            duration: 1100,
          },
          {
            id: 1,
            title: "Pull Requests e Issues",
            slug: "pull-requests-e-issues",
            watched: false,
            description: "Fluxo de contribuição e organização de projetos.",
            duration: 1000,
          },
        ],
      },
      {
        id: 3,
        title: "Automação e boas práticas",
        percentage: 0,
        lessons: [
          {
            id: 0,
            title: "Git Hooks e pré-commits",
            slug: "git-hooks-precommit",
            watched: false,
            description: "Automatize tarefas com Git.",
            duration: 1100,
          },
          {
            id: 1,
            title: "Commits semânticos",
            slug: "commits-semanticos",
            watched: false,
            description: "Padrões para manter histórico organizado.",
            duration: 900,
          },
        ],
      },
    ],
  },
];

export { courses };
